imports:
    - { resource: services/fieldtype_data_providers.yaml }
    - { resource: services/limitation_parsers.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\Behat\API\ContentData\ContentDataProvider:
         arguments:
            - '@ezpublish.api.service.content_type'
            - '@ezpublish.api.service.content'

    ezbehatbundle.api.facade.contentfacade:
        class: EzSystems\Behat\API\Facade\ContentFacade
        public: true

    ezbehatbundle.api.facade.contenttypefacade:
        class: EzSystems\Behat\API\Facade\ContentTypeFacade
        public: true

    ezbehatbundle.api.facade.rolefacade:
        class: EzSystems\Behat\API\Facade\RoleFacade
        public: true

    ezbehatbundle.api.facade.userfacade:
        class: EzSystems\Behat\API\Facade\UserFacade
        public: true

    ezbehatbundle.api.facade.languagefacade:
        class: EzSystems\Behat\API\Facade\LanguageFacade
        public: true

    ezbehatbundle.controller.exception:
        class: EzSystems\BehatBundle\Controller\ExceptionController
        public: true

    EzSystems\Behat\Core\Behat\ArgumentParser:
        public: true

#        ezbehatbundle.core.behat.languagefacade:
#            class: EzSystems\BehatBundle\Core\Behat\UrlParser
#            public: true

    EzSystems\BehatBundle\Command\CreateLanguageCommand:
        tags:
            - { name: console.command }

    EzSystems\BehatBundle\Command\TestSiteaccessCommand:
        arguments:
            $siteaccess: '@ezpublish.siteaccess'
        tags:
            - { name: console.command }
